Frontend: feat/games list
ramos-ph/cm42-media-critic pull request #7
Opened 2023-10-02 12:16 UTC by joaoGabriel55

Preview
![image](https://github.com/ramos-ph/cm42-media-critic/assets/23138717/a3eebf14-cd5a-476d-919f-d60d66c2901c)

2023-10-09 19:51 UTC, paulodiovani requested changes

2023-10-09 19:51 UTC, paulodiovani commented on frontend/package.json
>      "@vitest/coverage-v8": "^0.34.5",
why `vitest` instead of `jest`?
Does it come with `next` or was your choice? :thinking:

2023-10-09 19:51 UTC, paulodiovani commented on frontend/public/placeholder.jpg
This image could be smaller, right?

2023-10-09 19:51 UTC, paulodiovani commented on frontend/src/views/home/components/media-by-letter-filter/constants.ts
> +] as const;
What if we use Chinese or Hindi?

Just kidding :laughing:

2023-10-09 19:51 UTC, paulodiovani commented on frontend/src/views/home/components/games/games.tsx
> +]
This PR should be making requests, already.

2023-10-09 19:51 UTC, paulodiovani commented on frontend/src/shared/components/radio-group/radio-group.tsx
> +
I appreciate the idea of creating the shareable fields already, but since the initial story was about creating a game list only and we won't have a form, this must be left for a future PR.

- Create a second PR with only these form fields.
- Remove them from this PR
- Keep the commits concise, use rebase and squash/fixup as needed, to prevent commits from removing content previously added.

2023-10-19 14:13 UTC, ramos-ph commented on frontend/src/config/index.ts
> +export default config
Did you run Prettier? Some files have a NL, whereas others do not.

2023-10-19 14:13 UTC, ramos-ph commented on frontend/src/infrastructure/http-client/makeHttpClient.ts
> +    async get<T>(url: string): Promise<T> {
Cool usage of Generics!

2023-10-19 14:13 UTC, ramos-ph commented on frontend/src/shared/components/loading-spinner/loading-spinner.tsx
> +import React from 'react'
Still need to import React? I thought newer versions did not need this, unless it is a Next thing.

2023-10-19 14:13 UTC, ramos-ph commented on frontend/src/views/home/components/games/games.tsx
> +'use client'
What does this do?

2023-10-19 14:13 UTC, ramos-ph commented on frontend/src/views/home/components/games/useFetchGames.ts
> +    hasGames: (data?.length as number) > 0,
I would avoid assertion here. Let us guarantee this will never be null or undefined:

```suggestion
    hasGames: (data ?? []).length > 0,
```

2023-10-19 14:13 UTC, ramos-ph commented on frontend/src/views/home/home.tsx
> +      <MediaByLetterFilter />
We would need to move `useState<Alphabet>` to this file, and pass the state as props, yes? Or is there another way to share that state?

2023-10-20 20:45 UTC, joaoGabriel55 commented on frontend/src/views/home/components/games/games.tsx
> +'use client'
To tell to next framework, that component needs to be rendered only on the client side and not on the server.

2023-10-20 20:48 UTC, joaoGabriel55 commented on frontend/src/views/home/home.tsx
> +      <MediaByLetterFilter />
I think that for now, we can keep this state managed by `MediaByLetterFilter`, while we do not implement some API to filter games/media by start letter

2023-10-20 21:07 UTC, ramos-ph approved these changes

2023-10-20 21:14 UTC, merged